version: '3.8'
services:
  nginx:
    build                   : requirements/nginx
    volumes:
      - /tmp/iyamada/wordpress:/var/www/html
    ports:
      # - 8080:443
      - 8080:80
    depends_on:
      - wordpress
    container_name          : nginx
    environment:
      - NGINX_HOST=${DOMAIN_NAME}
      - NGINX_PORT=${NGINX_PORT}
    restart                 : always

  wordpress:
    build                   : requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - /tmp/iyamada/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST         : ${MYSQL_HOST}
      WORDPRESS_DB_USER         : ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD     : ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME         : ${MYSQL_DATABASE}
      WORDPRESS_ADMIN_USER      : ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_USER_PASS : ${WORDPRESS_ADMIN_USER_PASS}
      WORDPRESS_ADMIN_EMAIL     : ${WORDPRESS_ADMIN_EMAIL}
    container_name          : wordpress
    restart                 : always
    ports:
      - 9000:9000

  mariadb:
    build                   : requirements/mariadb
    volumes:
      - /tmp/iyamada/mariadb:/var/lib/mariadb
    env_file:
      - .env
    # environment:
    #   MARIADB_ROOT_PASSWORD : ${MYSQL_ROOT_PASSWORD}
    #   MARIADB_DATABASE      : ${MYSQL_DATABASE}
    #   MARIADB_USER          : ${MYSQL_USER}
    #   MARIADB_PASSWORD      : ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    container_name          : mariadb
    restart                 : always

volumes:
    mariadb: