version: '3.8'
services:
  nginx:
    build         : requirements/nginx
    container_name: nginx
    restart       : on-failure
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    networks:
      - frontend
    env_file:
      - .env
    ports:
      # - 8080:443
      - 8080:80

  wordpress:
    build         : requirements/wordpress
    container_name: wordpress
    restart       : on-failure
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks:
      - frontend
      - backend
    env_file:
      - .env
    ports:
      - 9000:9000

  mariadb:
    build          : requirements/mariadb
    container_name : mariadb
    restart        : on-failure
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    env_file:
      - .env
    ports:
      - 3306:3306

volumes:
    wp_data:
      driver: local
      driver_opts:
        type  : none
        o     : bind
        device: /Users/yamadaiori/data/wordpress
    db_data:
      driver: local
      driver_opts:
        type  : none
        o     : bind
        device: /Users/yamadaiori/data/mariadb

networks:
  frontend:
    driver: custom-driver-1
  backend:
    driver: custom-driver-2
    driver_opts:
      foo: "1"
      bar: "2"
